export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const GET_PRODUCTDATA  = 'GET_PRODUCTDATA'

export const LOADING_PRODUCT = 'LOADING_PRODUCT'
export const ERROR_PRODUCT = 'ERROR_PRODUCT'
