export const INCREMENT_COUNTER = 'INCREMENT_COUNTER'
export const DECREMENT_COUNTER = 'DECREMENT_COUNTER'

export const GET_PRODUCTDATA  = 'GET_PRODUCTDATA'
export const ADD_PRODUCTDATA  = 'ADD_PRODUCTDATA'
export const DELETE_PRODUCTDATA  = 'DELETE_PRODUCTDATA'
export const UPDATE_PRODUCTDATA  = 'UPDATE_PRODUCTDATA'

export const LOADING_PRODUCT = 'LOADING_PRODUCT'
export const ERROR_PRODUCT = 'ERROR_PRODUCT'

export const ADD_CATEGORYDATA = 'ADD_CATEGORYDATA'
export const GET_CATEGORYDATA = 'GET_CATEGORYDATA'
export const DELETE_CATEGORYDATA = 'DELETE_CATEGORYDATA'
export const UPDATE_CATEGORYDATA = 'UPDATE_CATEGORYDATA'

export const ERROR_CATEGORY = 'ERROR_CATEGORY'

